### ISSUE TITLE
想花钱学习下

### ISSUE THREAD

**Issue by guixin567** [real-stanford/universal_manipulation_interface#1]
有国内的大神，出一个视频课程吗，在国内怎么买这些硬件，怎么跑起来这个程序，最后使用demo演示下
愿意花钱跟着学习下

**Comment by marcuswuh** [comment]
可以加一下联系方式，我们团队正在复现。

**Comment by zhenjia-xu** [comment]
Tutorials of 3D printing and assembly are released.
https://youtu.be/x3ko0v_xwpg?si=cQnTKZEktMx3oPpf
https://youtu.be/EJmAg1Bnp-k?si=J-1acm4v7IPECbtQ
Code, CAD models, and data collection instructions can be found on the project website: https://umi-gripper.github.io/

**Comment by shiba-8ro** [comment]
@zhenjia-xu 
It's really cool that CAD data is being shared on OnShape. I immediately copied the project.

**Comment by kafei123456** [comment]
> 可以加一下联系方式，我们团队正在复现。

你们复现成功了吗？

**Comment by guixin567** [comment]
> 可以加一下联系方式，我们团队正在复现。

wx:18823202393，大佬加下我跟着你学习
