### ISSUE TITLE
about the example data

### ISSUE THREAD

**Issue by songhat** [real-stanford/universal_manipulation_interface#10]
Hi @cheng-chi ,

I am going download the data using this command:
`(umi)$ wget --recursive --no-parent --no-host-directories --cut-dirs=2 --relative --reject="index.html*" https://real.stanford.edu/umi/data/example_demo_session/`

I'm having a network problem:
```
--2024-03-03 16:30:23--  https://real.stanford.edu/umi/data/example_demo_session/
Connecting to 127.0.0.1:7890... connected.
Unable to establish SSL connection.
```
Is there any other way to download?

**Comment by cheng-chi** [comment]
Sorry @songhat our lab's website is down! We are working on a fix.

**Comment by cheng-chi** [comment]
@songhat The website should be fixed! Please try again
