### ISSUE TITLE
GoPro Hero10 replace GoPro Hero 9

### ISSUE THREAD

**Issue by cjlong1213** [real-stanford/universal_manipulation_interface#11]
Hi @cheng-chi ,

Thanks for sharing the amazing work!
Can we use **GoPro Hero 10** replace **GoPro Hero 9** since we can not order GoPro Hero 9?

Thanks

**Comment by cheng-chi** [comment]
@cjlong1213 Yes, GoPro Hero 10 should work out of the box!

**Comment by lakomchik** [comment]
Hi @cheng-chi.

Is it also possible to use **GoPro Hero 11** or **GoPro Hero 12** instead of  **GoPro Hero 9**?

**Comment by cheng-chi** [comment]
@lakomchik I haven't tried on Hero 11 and hero 12 yet. While the code should work for them, you will likley need calibrating camera and IMU parameteres using [OpenImuCameraCalibrator](https://github.com/urbste/OpenImuCameraCalibrator). Hero 11 and 12 have updated sensors and lenses compared to 9 and 10.

**Comment by lakomchik** [comment]
@cheng-chi Thank you for detailed answer!
