### ISSUE TITLE
uvccamera.data assignment issue

### ISSUE THREAD

**Issue by Siidej** [real-stanford/universal_manipulation_interface#13]
Hello, thank you for your brilliant work,
But I was confused when I checked this [code snippet](https://github.com/real-stanford/universal_manipulation_interface/blob/e02f7a960fef9b529c0af10d6452072cfd53819f/umi/real_world/uvc_camera.py#L248-L249). Is this a wrong assignment or just the naming prob.?

**Comment by cheng-chi** [comment]
Good catch!

**Comment by cheng-chi** [comment]
Fixed
