### ISSUE TITLE
Can't download data/zarr_datasets

### ISSUE THREAD

**Issue by cc299792458** [real-stanford/universal_manipulation_interface#17]
Hi, congratulations on the amazing work!

I tried to download the zarr_datasets, but it seems I don't have the access. Then I tried to checked it out in the website and it said I don't have the permission. Is that a problem of my network or just the dataset is not currently released to public?

Thanks

**Comment by cheng-chi** [comment]
I should be fixed! Please try again

**Comment by cc299792458** [comment]
Yeah it works. Thanks!
