### ISSUE TITLE
GoPro Media Mod

### ISSUE THREAD

**Issue by Yingdong-Hu** [real-stanford/universal_manipulation_interface#25]
Hi @cheng-chi,
Why do I need a GoPro Media Mod when deploying on the real robot? It seems that the GoPro in the video on your website does not have GoPro Media Mod installed.
<img width="914" alt="image" src="https://github.com/real-stanford/universal_manipulation_interface/assets/36184713/57f15a54-9e14-419c-9ee0-665d50e70a7e">

**Comment by sirwart** [comment]
That GoPro has the media mod installed. The way you can tell is that there are no mini-HDMI ports on the back of the GoPro to plug into in order to get the live video feed from the camera.
