### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by nicrusso7** [real-stanford/universal_manipulation_interface#4]
Hi there,

first of all thank you for sharing this amazing work!

I was wondering what is the minimum required setup in terms of GPUs/RAM to train the model?

I saw in your paper you guys are using 4/8 A100, is there any chance to train the model using consumer GPUs?

Thanks

**Comment by cheng-chi** [comment]
Hi @nicrusso7 I just updated the README.md with sample sample data and training instructions for 3090. Training on consumer grade GPUs are entirely feasible, just a little slower.

**Comment by nicrusso7** [comment]
Amazing, thanks! 

I've a RTX 3070 with just 8GB vRAM and 16GB system RAM, not sure the model will fits but I'll try!
