### ISSUE TITLE
dose the location of the marker matter during step 2(Mapping Video)?

### ISSUE THREAD

**Issue by lturing** [real-stanford/universal_manipulation_interface#50]
from my understanding, the marker can provide the transformation from camera to tag, and the slam can provide the transformation from camera to slam world, together, we can get the transformation from tag to slam world. and during step 4(Data Collection), we can get camera to tag, and the camera to flange, together, we can get the transformation from tag to flange. my question is when we perform multi-times step2,  the location of the tag will diff, and the coordination system will change, which will harm the training of policy model.

**Comment by ArenaGrenade** [comment]
Hey! Did you find any issues due to this?
