### ISSUE TITLE
slam pipeline enable_gui

### ISSUE THREAD

**Issue by liaraaaaaaa** [real-stanford/universal_manipulation_interface#69]
when I tried to set 'enable_gui' to true,  subprocess was something wrong

**Comment by liaraaaaaaa** [comment]
I give up docker, and use source code of ORB_SLAM3

**Comment by MarioCavero** [comment]
Have you tried printing what the docker command will give, copying, pasting it to the console and running the docker command directly on command line and not with the 02 or 03_slam script, with the proper enable_gui? It does not work straight to me as well, but printing the command that subprocess runs, copying it and running it directly to the command line (taking out commas or [ ] symbols), will run it properly as a docker command and enable_gui will work. @liaraaaaaaa
