### ISSUE TITLE
Help with kinematic based data filtering

### ISSUE THREAD

**Issue by sirwart** [real-stanford/universal_manipulation_interface#7]
I'm trying to replicate this paper on my own hardware, which is a ViperX 300 6 DoF. I'm running into a problem where my policy is generating a lot of singularities, which I imagine is partly due to the ViperX having more of them than the robots you used in the paper.

However in the paper you mentioned that you used kinematics based data filtering to train the policy. I didn't see any place to incorporate the ViperX's kinematics into the code, so I don't think I did any filtering when I trained my policy. Could you give me any pointers on how you achieved this?

**Comment by cheng-chi** [comment]
Hi @sirwart, we did task-specific filtering around [this line](https://github.com/real-stanford/universal_manipulation_interface/blob/e02f7a960fef9b529c0af10d6452072cfd53819f/scripts_slam_pipeline/06_generate_dataset_plan.py#L628) with [ur_ikfast](https://github.com/cambel/ur_ikfast), which is not compatible with ViperX.
Please feel free to submit a PR once you figure out kinematics based data filtering with ViperX!
